services:
  sails-api:
    build: sails-api
    command: npm run dev
    volumes:
      - ./sails-api:/app
    environment:
      PORT: 8080
      NODE_ENV: development
    ports:
      - 8080:8080
  feathers-logs-service:
    build: feathers-logs-service
    command: npm run dev
    volumes:
      - ./feathers-logs-service:/app
    environment:
      PORT: 8081
      NODE_ENV: development
    ports:
      - 8081:8081
  mongo:
    image: mongo:8.0.10
  mongo-express:
    image: mongo-express:1.0.0-alpha
    ports:
      - 8088:8081
